feat(julinux): ship flatpak, gnome-software + flathub pre-enabled
- Add flatpak, gnome-software-plugin-flatpak, xdg-desktop-portal(-gtk)
- Pre-seed Flathub via /etc/flatpak/remotes.d (auto-imported on first use)

diff --git a/install-julinux/bljulinux13X b/install-julinux/bljulinux13X
--- a/install-julinux/bljulinux13X
+++ b/install-julinux/bljulinux13X
@@ -46,10 +46,10 @@ lb config \
 echo "accountsservice arc-theme asunder atril breeze-gtk-theme breeze-icon-theme dconf-cli galculator geany gnome-keyring gnome-nettool gnome-system-tools greybird-gtk-theme gthumb guvcview gvfs-backends gvfs-fuse light-locker lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings mousepad network-manager-gnome network-manager-openconnect-gnome network-manager-openvpn-gnome pavucontrol pulseaudio remmina simple-scan system-config-printer tango-icon-theme transmission-gtk xarchiver xfce4 xfce4-goodies xfce4-power-manager xfce4-terminal xscreensaver" > $WKDIR/$BLDDIR/config/package-lists/xfcedesktop.list.chroot
 
 # Install JULinux system packages (adapted from StormD/StormOS)
-echo "accountsservice apt-transport-https bleachbit build-essential cdtool cdrdao cdrskin chromium cifs-utils clonezilla cryptsetup cryptsetup-initramfs cups cups-filters curl dbus-user-session dbus-x11 debconf debhelper dh-autoreconf dialog dirmngr dkms dos2unix dosbox dvdauthor exfatprogs faac faad fakeroot fastfetch ffmpeg filezilla flac foomatic-db foomatic-db-engine frei0r-plugins fuse3 gdebi ghostscript gnome-disk-utility gparted grsync grub-common grub2-common gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-plugins-good gvfs gvfs-backends gvfs-fuse hardinfo haveged hplip-gui htop hunspell-en-us hyphen-en-us iftop im-config inxi iw keepassxc lame less libqt5opengl5t64 libreoffice-calc libreoffice-draw libreoffice-impress libreoffice-writer libreoffice-gtk3 libreoffice-help-en-us libnss-mdns libsmbclient0 libxcb-xtest0 libxvidcore4 linux-headers-amd64 live-build lsb-release lshw meld mencoder menu mjpegtools mpg321 mpv mtools mythes-en-us netcat-openbsd openconnect openvpn openvpn-systemd-resolved os-prober p7zip-full p7zip-rar papirus-icon-theme pciutils perl plymouth plymouth-label plymouth-themes plymouth-x11 printer-driver-gutenprint python3-pyqt5 rar samba-common-bin smbclient smplayer smplayer-l10n smplayer-themes soundconverter sox squashfs-tools streamripper sudo synaptic syslinux syslinux-common systemd-timesyncd testdisk timeshift twolame upower unrar unzip webext-keepassxc-browser wget x11-common x265 x264 xauth xclip xdg-utils xorg xserver-xorg-input-all xserver-xorg-video-all xorriso xterm zip zstd" > $WKDIR/$BLDDIR/config/package-lists/morepackages.list.chroot
+echo "accountsservice apt-transport-https bleachbit build-essential cdtool cdrdao cdrskin chromium cifs-utils clonezilla cryptsetup cryptsetup-initramfs cups cups-filters curl dbus-user-session dbus-x11 debconf debhelper dh-autoreconf dialog dirmngr dkms dos2unix dosbox dvdauthor exfatprogs faac faad fakeroot fastfetch ffmpeg filezilla flac foomatic-db foomatic-db-engine frei0r-plugins fuse3 gdebi ghostscript gnome-disk-utility gnome-software gnome-software-plugin-flatpak flatpak gparted grsync grub-common grub2-common gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-plugins-good gvfs gvfs-backends gvfs-fuse hardinfo haveged hplip-gui htop hunspell-en-us hyphen-en-us iftop im-config inxi iw keepassxc lame less libqt5opengl5t64 libreoffice-calc libreoffice-draw libreoffice-impress libreoffice-writer libreoffice-gtk3 libreoffice-help-en-us libnss-mdns libsmbclient0 libxcb-xtest0 libxvidcore4 linux-headers-amd64 live-build lsb-release lshw meld mencoder menu mjpegtools mpg321 mpv mtools mythes-en-us netcat-openbsd openconnect openvpn openvpn-systemd-resolved os-prober p7zip-full p7zip-rar papirus-icon-theme pciutils perl plymouth plymouth-label plymouth-themes plymouth-x11 printer-driver-gutenprint python3-pyqt5 rar samba-common-bin smbclient smplayer smplayer-l10n smplayer-themes soundconverter sox squashfs-tools streamripper sudo synaptic syslinux syslinux-common systemd-timesyncd testdisk timeshift twolame upower unrar unzip webext-keepassxc-browser wget x11-common x265 x264 xauth xclip xdg-utils xorg xserver-xorg-input-all xserver-xorg-video-all xorriso xterm zip zstd" > $WKDIR/$BLDDIR/config/package-lists/morepackages.list.chroot
 
 # Install JULinux-specific packages (switcheroo-control, nvidia-detect, broadcom)
-echo "switcheroo-control nvidia-detect broadcom-sta-dkms bluez blueman network-manager-gnome pavucontrol pipewire pipewire-pulse wireplumber kitty kitty-terminfo" > $WKDIR/$BLDDIR/config/packages.list.chroot
+echo "switcheroo-control nvidia-detect broadcom-sta-dkms bluez blueman network-manager-gnome pavucontrol pipewire pipewire-pulse wireplumber kitty kitty-terminfo xdg-desktop-portal xdg-desktop-portal-gtk" > $WKDIR/$BLDDIR/config/packages.list.chroot
 
 # Install firmware
 echo "atmel-firmware bluez-firmware firmware-linux-free midisport-firmware firmware-misc-nonfree firmware-amd-graphics firmware-atheros firmware-bnx2 firmware-bnx2x firmware-brcm80211 firmware-cavium firmware-intel-sound firmware-iwlwifi firmware-libertas firmware-linux firmware-linux-nonfree firmware-misc-nonfree firmware-myricom firmware-netronome firmware-netxen firmware-qcom-media firmware-qcom-soc firmware-qlogic firmware-realtek firmware-samsung firmware-siano firmware-ti-connectivity firmware-sof-signed firmware-zd1211 firmware-b43-installer broadcom-sta-dkms" > $WKDIR/$BLDDIR/config/package-lists/firmware.list.chroot
@@ -81,6 +81,10 @@ cp -r $WKDIR/$FLDIR/bootloaders/ $WKDIR/$BLDDIR/config/
 cp -r $WKDIR/$FLDIR/ $WKDIR/$BLDDIR/config/includes.chroot/usr/share/
 cp -r $WKDIR/$FLDIR/modprobe.d/ $WKDIR/$BLDDIR/config/includes.chroot/etc/
 cp $WKDIR/$FLDIR/hooks/* $WKDIR/$BLDDIR/config/hooks/normal/ 2>/dev/null || true
+
+# Pre-seed the Flathub remote (auto-imported by flatpak on first use)
+mkdir -p $WKDIR/$BLDDIR/config/includes.chroot/etc/flatpak/remotes.d/
+curl -fsSL https://dl.flathub.org/repo/flathub.flatpakrepo -o $WKDIR/$BLDDIR/config/includes.chroot/etc/flatpak/remotes.d/flathub.flatpakrepo || echo "WARNING: could not download flathub.flatpakrepo - Flathub will need manual setup"
 cp $WKDIR/$FLDIR/scripts/* $WKDIR/$BLDDIR/config/includes.chroot/usr/local/bin/
 cp $WKDIR/$FLDIR/icons/* $WKDIR/$BLDDIR/config/includes.chroot/usr/share/icons/default/
 cp $WKDIR/$FLDIR/backgrounds/* $WKDIR/$BLDDIR/config/includes.chroot/usr/share/backgrounds/
